logging:
  config: classpath:logback.xml
server:
  port: 9011

spring:
  profiles:
    active: local

xxl:
  job:
    accessToken: default_token
    admin:
      addresses: http://127.0.0.1:9001/qiin-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999

mybatis:
  mapperLocations: classpath:com.xxl.job/mapper/*.xml
  typeAliasesPackage: com/xxl/job/domain
