spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.208.3:3306/xxl_job
    username: qinpeiyang
    password: qinpeiyang
  mail:
    host: smtp.qq.com
    username: 827989320@qq.com
    password: rtxbqnmadfprbahh
